lainsce/notejot

- .gitignore
- com.github.lainsce.notejot.json
- meson/post_install.py
Execute the commands below:
**1 - command:**  _(Responsible for downloading the libraries, their application and then compiling them)_
Note: Change line 95, 96 for your repository configuration. 
* _If you do not know sha256, just run the command it will generate an error and displaying the correct sha256._
```
flatpak-builder app-dir com.github.lainsce.notejot.json --force-clean
```
**2 - command:**  _(This starts flatpak build)_
```
flatpak-builder --run app-dir com.github.lainsce.notejot.json com.github.lainsce.notejot
```
**Warning: _I removed the cache configuration of the icons in the file post_install.py (I could not configure with it)_**
> Configuration to create the application in flatpak

- po/LINGUAS
- po/es.po
We are neighbors, I am from Peru, helping with the translation.
> Add spanish traslate

- po/LINGUAS
- po/fr.po
Adds fr.po, and updates LINGUAS.
> Adding French translation

- data/com.github.lainsce.notejot.desktop
Added polish comment for desktop entry.
> com.github.lainsce.notejot.desktop

- data/com.github.lainsce.notejot.appdata.xml
> Fix appstream license

- po/LINGUAS
- po/nl_NL.po
> Add Dutch translation

- src/Application.vala
Enabling: 
- <kbd>ctrl</kbd>+<kbd>n</kbd> create new note
- <kbd>ctrl</kbd>+<kbd>w</kbd> deleting current note
> Adding more keyboard shortcuts

- po/ja.po
I've also translated Notejot into Japanese.
> Translated Notejot into Japanese

- data/meson.build
> Remove font assignment from building

- data/meson.build
Just now I found I've forgot adding these lines in #89…
> Fix desktop file is not installed

- meson.build
> fix postinstall script

- src/MainWindow.vala
- src/Services/NoteManager.vala
- src/Services/Storage.vala
**Changes**
**Issue that needs to be solved**
> Store pinned state

- po/LINGUAS
- po/extra/LINGUAS
- po/extra/nl.po
- po/nl.po
> Updated Dutch translations + renamed nl_NL.po to nl.po

- po/es.po
- po/io.github.lainsce.Notejot.pot
- src/MainWindow.vala
- src/Widgets/Note.vala
> Update Spanish translation

- data/ui/main_window.ui
- src/MainWindow.vala
This will fix an issue wherein the main window is missing a title button in folded state. Plus it cleans some code :D
> use bindings to hide & show back buttons and close buttons

- data/io.github.lainsce.Notejot.gschema.xml
- src/MainWindow.vala
- src/Settings.vala
This one fixes #263. Although this implementation is not crash-proof, is faster than previous one and covers maximized-window cases
> Remember window size #263

- build-aux/flatpak/io.github.lainsce.Notejot.json
- data/io.github.lainsce.Notejot.appdata.xml.in
Another easy one that should have been commited with cefd0f00857c83004a39b7256610cf2f09ecff97 😅
EDIT: I've changed more options now.
> Add more metadata information

- data/io.github.lainsce.Notejot.appdata.xml.in
- data/meson.build
- src/MainWindow.vala
As Notejot's name is unique, the string has become untranslatable, the only left place is desktop entry which can't be marked as untranslatable.
Code in MainWindow seemed duplicated to me, but I could be wrong.
> Few enhancements

- io.github.lainsce.Notejot.Devel.json
> build: fix Notejot's module source

- data/icons/io.github.lainsce.Notejot.Devel.svg
- data/meson.build
- io.github.lainsce.Notejot.Devel.json
- meson.build
- src/Application.vala
- src/Config.vapi
- src/MainWindow.vala
Commit message:
```
- Add vcs taggging for development builds.
- Name prefix in development builds is now a suffix to match
desktop file name.
```
> build: minor changes

- data/io.github.lainsce.Notejot.appdata.xml.in
- io.github.lainsce.Notejot.doap
Changes the description so that it specifies the most important features of Notejot, possibly the wording of the text could be improved or I have forgotten something, let me know what you think :)
Edit: Should I change the description in .doap as well?
> appdata: detail features in the description

- data/io.github.lainsce.Notejot.metainfo.xml.in
- meson.build
- po/meson.build
- src/ViewModels/NoteViewModel.vala
Follow up to c60c27eb4aa22c610c31993734f778883d96446e
Some things I forgot in the previous PR 🙃
> build: use app_id for gettext

- po/cs.po
I noticed that the Czech translation is incomplete (there were only 2 words translated), so I completed it. It should be 100% translated now.
> Full Czech translation

- po/pt_BR.po
The previous translation was incomplete and used the same sentence for lots of messages
> Finished and reviewed translation of your app for Brazilian Portuguese

- po/ja.po
> update japanese translations

- po/LINGUAS
- po/oc.po
Translation file + modification to the language list
> Translated your app for OC

- po/POTFILES
- po/io.github.lainsce.Notejot.pot
- src/MainWindow.vala
- src/Views/TrashContentView.vala
- Update POTFILES
- Do not use empty msgid to prevent xgettext warning
- Update .pot
- Use ngettext instead of concatenating strings
> Improve l10n
